AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SoccerScoresApi
Parameters:
  Stage:
    Description: The environment this application is deployed to (should be dev, staging
      or prod)
    Default: prod
    Type: String
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  ScoreUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SoccerScoresApi::SoccerScoresApi.Functions.UpsertMatchesFunction::Execute
      Runtime: dotnetcore3.1
      CodeUri: s3://anchoragewonder-deploys/bea9029a06a9c4c03f70500b51de2701
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /update/
            Method: POST
  FixtureUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SoccerScoresApi::SoccerScoresApi.Functions.UpsertFixturesFunction::Execute
      Runtime: dotnetcore3.1
      CodeUri: s3://anchoragewonder-deploys/bea9029a06a9c4c03f70500b51de2701
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /update/fixtures/
            Method: POST
  EmptyGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SoccerScoresApi::SoccerScoresApi.Functions.GetMatchesFunction::Execute
      Runtime: dotnetcore3.1
      CodeUri: s3://anchoragewonder-deploys/bea9029a06a9c4c03f70500b51de2701
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /teams/
            Method: GET
  MatchesGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SoccerScoresApi::SoccerScoresApi.Functions.GetMatchesFunction::Execute
      Runtime: dotnetcore3.1
      CodeUri: s3://anchoragewonder-deploys/bea9029a06a9c4c03f70500b51de2701
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /teams/{name}
            Method: GET
Outputs:
  ApiURL:
    Description: API endpoint URL
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ServerlessRestApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/
        - Ref: Stage
